version: '3'
name: fastapi-vue-boilerplate
services:  
  fastapi_backend:
    build: ./backend
    image: fastapi_app
    container_name: fastapi_app
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app/

    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  vue_frontend:
    build: ./frontend
    image: vue_app
    container_name: vue_app
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - fastapi_backend
